openapi: 3.1.0
info:
  title: Track API
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /tracks:
    get:
      summary: トラック一覧を取得する
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TrackRequired"
      operationId: getTracks
      parameters:
        - schema:
            type: string
          in: query
          name: author_id
    parameters: []
  "/tracks/{track_id}":
    parameters:
      - $ref: "#/components/parameters/track_id"
    get:
      summary: トラックを取得する
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrackRequired"
      operationId: getTrack
    patch:
      summary: トラックを更新する
      operationId: updateTrack
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrackRequired"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Track"
  "/authors/{author_id}":
    parameters:
      - $ref: "#/components/parameters/author_id"
    get:
      summary: 著者を取得する
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorRequired"
      operationId: getAuthor
components:
  schemas:
    Track:
      title: Track
      type: object
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
        description:
          type: string
        author_id:
          type: string
        thumbnail:
          type: string
        length:
          type: integer
        number_of_views:
          type: integer
      required:
        - id
    TrackRequired:
      title: TrackRequired
      allOf:
        - $ref: "#/components/schemas/Track"
        - type: object
          properties:
            title:
              type: string
            author_id:
              type: string
          required:
            - title
            - author_id
    Author:
      title: Author
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        photo:
          type: string
      required:
        - id
    AuthorRequired:
      title: AuthorRequired
      allOf:
        - $ref: "#/components/schemas/Author"
        - type: object
          properties:
            name:
              type: string
          required:
            - name
  parameters:
    track_id:
      name: track_id
      in: path
      required: true
      schema:
        type: string
    author_id:
      name: author_id
      in: path
      required: true
      schema:
        type: string
